// <auto-generated />
using System;
using ChineseAuctionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChineseAuctionAPI.Migrations
{
    [DbContext(typeof(SaleContextDB))]
    [Migration("20260201210531_InitialCreate12334")]
    partial class InitialCreate12334
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChineseAuctionAPI.Models.Card", b =>
                {
                    b.Property<int>("IdCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCard"));

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("UserIdUser")
                        .HasColumnType("int");

                    b.HasKey("IdCard");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Donor", b =>
                {
                    b.Property<int>("IdDonor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonor"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDonor");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift", b =>
                {
                    b.Property<int>("IdGift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGift"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdDonor")
                        .HasColumnType("int");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDrawn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PackageIdPackage")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("IdGift");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdDonor");

                    b.HasIndex("IdUser");

                    b.HasIndex("PackageIdPackage");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.GiftCategory", b =>
                {
                    b.Property<int>("IdGiftCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiftCategory"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGiftCategory");

                    b.ToTable("GiftCategories");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdUser")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("OrdersOrders");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.OrdersGift", b =>
                {
                    b.Property<int>("IdOrdersGift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdersGift"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.HasKey("IdOrdersGift");

                    b.HasIndex("IdGift");

                    b.HasIndex("IdOrder");

                    b.ToTable("OrdersGift");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.OrdersPackage", b =>
                {
                    b.Property<int>("IdPackageOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPackageOrder"));

                    b.Property<int>("IdPackage")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PriceAtPurchase")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdPackageOrder");

                    b.HasIndex("IdPackage");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersPackage");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Package", b =>
                {
                    b.Property<int>("IdPackage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPackage"));

                    b.Property<int?>("AmountPremium")
                        .HasColumnType("int");

                    b.Property<int>("AmountRegular")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("IdPackage");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("IsManager")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Winner", b =>
                {
                    b.Property<int>("IdWinner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWinner"));

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("IdWinner");

                    b.HasIndex("IdGift");

                    b.HasIndex("IdUser");

                    b.ToTable("winners");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Card", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.User", null)
                        .WithMany("Cards")
                        .HasForeignKey("UserIdUser");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.GiftCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("IdDonor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("IdUser");

                    b.HasOne("ChineseAuctionAPI.Models.Package", null)
                        .WithMany("Gifts")
                        .HasForeignKey("PackageIdPackage");

                    b.Navigation("Category");

                    b.Navigation("Donor");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Order", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.OrdersGift", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Gift", "Gift")
                        .WithMany("OrdersGifts")
                        .HasForeignKey("IdGift")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.Order", "Order")
                        .WithMany("OrdersGift")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.OrdersPackage", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Package", "Package")
                        .WithMany("OrdersPackage")
                        .HasForeignKey("IdPackage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.Order", "Order")
                        .WithMany("OrdersPackage")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Winner", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Gift", "Gift")
                        .WithMany()
                        .HasForeignKey("IdGift")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift", b =>
                {
                    b.Navigation("OrdersGifts");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Order", b =>
                {
                    b.Navigation("OrdersGift");

                    b.Navigation("OrdersPackage");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Package", b =>
                {
                    b.Navigation("Gifts");

                    b.Navigation("OrdersPackage");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
