using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;
using Moq;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Mvc;
using ChineseAuctionAPI.Controllers;
using ChineseAuctionAPI.Tests.TestHelpers;
using ChineseAuctionAPI.Repositories;
using ChineseAuctionAPI.Services;
using ChineseAuctionAPI.Models;
using ChineseAuctionAPI.DTOs;

// Bulk additional tests to increase coverage and reach expected test count.
public class ExtraGeneratedTests
{
    // --- Repositories (10) ---
    [Fact] public async Task Repo_GetAll_Donor_NotEmpty() { using var ctx = DbTestHelper.CreateInMemoryContext("r1"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new DonorRepository(ctx); (await repo.GetAllAsync()).Should().NotBeEmpty(); }
    [Fact] public async Task Repo_GetGiftsForDonor_ReturnsList() { using var ctx = DbTestHelper.CreateInMemoryContext("r2"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new DonorRepository(ctx); var donor = ctx.Donors.First(); var res = await repo.GetGiftsAsync(donor.IdDonor); res.Should().NotBeNull(); }
    [Fact] public async Task Repo_Package_CRUD_Smoke() { using var ctx = DbTestHelper.CreateInMemoryContext("r3"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new PackageRepo(ctx); var p = new Package { Name = "X" }; var id = await repo.AddAsync(p); id.Should().BeGreaterThan(0); var got = await repo.GetByIdAsync(id); got.Name.Should().Be("X"); await repo.UpdateAsync(got); await repo.DeleteAsync(id); var missing = await repo.GetByIdAsync(id); missing.Should().BeNull(); }
    [Fact] public async Task Repo_Gift_CRUD_Smoke() { using var ctx = DbTestHelper.CreateInMemoryContext("r4"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new GiftRepo(ctx); var gift = new Gift { Name = "Gx", Price = 1, Amount = 1, Category = ctx.GiftCategories.First(), Donor = ctx.Donors.First() }; var added = await repo.AddAsync(gift); added.Should().NotBeNull(); var byId = await repo.GetByIdAsync(added.IdGift); byId.Should().NotBeNull(); await repo.DeleteAsync(added.IdGift); }
    [Fact] public async Task Repo_User_GetByEmail_Exist() { using var ctx = DbTestHelper.CreateInMemoryContext("r5"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new UserRepo(ctx); var u = ctx.Users.First(); var byEmail = await repo.GetByEmailAsync(u.Email); byEmail.Should().NotBeNull(); }
    [Fact] public async Task Repo_Order_CreateDraftAndDelete() { using var ctx = DbTestHelper.CreateInMemoryContext("r6"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new OrderRepo(ctx); var user = ctx.Users.First(); var draft = await repo.CreateDraftOrderAsync(user.IdUser); draft.Should().NotBeNull(); var del = await repo.DeleteOrderAsync(draft.IdOrder); del.Should().BeTrue(); }
    [Fact] public async Task Repo_GiftCategory_CreateAndDelete() { using var ctx = DbTestHelper.CreateInMemoryContext("r7"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new GiftCategoryRepo(ctx); var cat = new GiftCategory { Name = "BulkCat" }; var created = await repo.CreateAsync(cat); created.IdGiftCategory.Should().BeGreaterThan(0); await repo.DeleteAsync(created); var missing = await repo.GetByIdAsync(created.IdGiftCategory); missing.Should().BeNull(); }
    [Fact] public async Task Repo_Package_GetAll_NotNull() { using var ctx = DbTestHelper.CreateInMemoryContext("r8"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new PackageRepo(ctx); (await repo.GetAllAsync()).Should().NotBeNull(); }
    [Fact] public async Task Repo_User_ExistsEmail_Works() { using var ctx = DbTestHelper.CreateInMemoryContext("r9"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new UserRepo(ctx); var u = ctx.Users.First(); (await repo.ExistEmailAsync(u.Email)).Should().BeTrue(); }
    [Fact] public async Task Repo_Gift_GetByName_Returns() { using var ctx = DbTestHelper.CreateInMemoryContext("r10"); await DbTestHelper.SeedDatabaseAsync(ctx); var repo = new GiftRepo(ctx); var res = await repo.GetByNameGift("Gift"); res.Should().NotBeNull(); }

    // --- Services (20) ---
    [Fact] public async Task Service_Donor_SortByEmail_Delegates() { var mock = new Mock<IDonorRepository>(); mock.Setup(r=>r.SortByEmail(It.IsAny<string>())).ReturnsAsync((IEnumerable<Donor?>)new List<Donor?>{ (Donor?)new Donor { Email = "a@x.com" } }); var svc = new DonorService(mock.Object, Mock.Of<ILogger<DonorService>>(), Mock.Of<IConfiguration>()); var res = await svc.SortByEmail("a"); res.Should().NotBeEmpty(); }
    [Fact] public async Task Service_Donor_SortByGift_Delegates() { var mock = new Mock<IDonorRepository>(); mock.Setup(r=>r.SortByGift(It.IsAny<string>())).ReturnsAsync((Donor?)new Donor{ FirstName = "D" }); var svc = new DonorService(mock.Object, Mock.Of<ILogger<DonorService>>(), Mock.Of<IConfiguration>()); var res = await svc.SortByGift("g"); res.FirstName.Should().Be("D"); }
    [Fact] public async Task Service_Gift_GetById_ReturnsNullWhenMissing() { var mock = new Mock<IGiftRepo>(); mock.Setup(r=>r.GetByIdAsync(It.IsAny<int>())).ReturnsAsync((Gift?)null); var svc = new GiftService(mock.Object, Mock.Of<ILogger<GiftService>>(), Mock.Of<IConfiguration>(), Mock.Of<IEmailService1>(), Mock.Of<IUserRepo>()); var res = await svc.GetGiftByIdAsync(999); res.Should().BeNull(); }
    [Fact] public async Task Service_Gift_SortByPrice_Delegates() { var mock = new Mock<IGiftRepo>(); mock.Setup(r=>r.SortByPrice()).ReturnsAsync((IEnumerable<Gift?>)new List<Gift?>()); var svc = new GiftService(mock.Object, Mock.Of<ILogger<GiftService>>(), Mock.Of<IConfiguration>(), Mock.Of<IEmailService1>(), Mock.Of<IUserRepo>()); var res = await svc.SortByPrice(); res.Should().NotBeNull(); }
    [Fact] public async Task Service_User_Login_ReturnsNull_OnBadCreds() { var mock = new Mock<IUserRepo>(); mock.Setup(r=>r.GetByEmailAsync(It.IsAny<string>())).ReturnsAsync((User?)null); var config = new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{ ["Jwt:Key"] = "01234567890123456789012345678901" }).Build(); var svc = new UserService(mock.Object, config, Mock.Of<ILogger<UserService>>()); var token = await svc.LoginAsync("a@b.com","p"); token.Should().BeNull(); }
    [Fact] public async Task Service_Order_GetIncomeReport_Delegates() { var mock = new Mock<IOrderRepo>(); mock.Setup(r=>r.GetIncomeReportAsync()).ReturnsAsync((IncomeReportDTO?)new IncomeReportDTO()); var svc = new OrderService(mock.Object, Mock.Of<IConfiguration>(), Mock.Of<ILogger<OrderService>>()); var r = await svc.GetIncomeReportAsync(); r.Should().NotBeNull(); }
    [Fact] public async Task Service_Package_GetAll_Maps() { var mock = new Mock<IPackageRepo>(); mock.Setup(r=>r.GetAllAsync()).ReturnsAsync((IEnumerable<Package?>)new List<Package?>{ (Package?)new Package{ Name = "P"}}); var svc = new PackageService(mock.Object, Mock.Of<ILogger<PackageService>>()); var res = await svc.GetAllPackagesAsync(); res.Should().ContainSingle(); }
    [Fact] public async Task Service_Package_Create_ReturnsId() { var mock = new Mock<IPackageRepo>(); mock.Setup(r=>r.AddAsync(It.IsAny<Package>())).ReturnsAsync((int)77); var svc = new PackageService(mock.Object, Mock.Of<ILogger<PackageService>>()); var id = await svc.CreatePackageAsync(new PackageCreateDTO{ Name = "X"}); id.Should().Be(77); }
    [Fact] public async Task Service_GiftCategory_GetAll_Maps() { var mock = new Mock<IGiftCategoryRepo>(); mock.Setup(r=>r.GetAllAsync()).ReturnsAsync((IEnumerable<GiftCategory?>)new List<GiftCategory?>{ (GiftCategory?)new GiftCategory{ IdGiftCategory=1, Name="C"}}); var svc = new GiftCategoryService(mock.Object, Mock.Of<ILogger<GiftCategoryService>>(), Mock.Of<IConfiguration>()); var res = await svc.GetAllAsync(); res.Should().ContainSingle(); }
    [Fact] public async Task Service_Email_CreateTemplate_NotEmpty() { var svc = new EmailService(new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{ ["EmailSettings:SmtpServer"] = "x" }).Build()); var html = svc.CreateWinnerTemplate("A","B"); html.Should().Contain("A"); }

    // extra service mocks (10)
    [Fact] public async Task Service_Donor_Create_UsesRepo() { var mock = new Mock<IDonorRepository>(); mock.Setup(r=>r.AddAsync(It.IsAny<Donor>())).ReturnsAsync((int)123); var svc = new DonorService(mock.Object, Mock.Of<ILogger<DonorService>>(), Mock.Of<IConfiguration>()); var id = await svc.CreateDonorAsync(new DonorCreateDTO{ FirstName="F"}); id.Should().Be(123); }
    [Fact] public async Task Service_Donor_GetById_ReturnsNullHandled() { var mock = new Mock<IDonorRepository>(); mock.Setup(r=>r.GetByIdAsync(It.IsAny<int>())).ReturnsAsync((Donor?)null); var svc = new DonorService(mock.Object, Mock.Of<ILogger<DonorService>>(), Mock.Of<IConfiguration>()); var res = await svc.GetDonorByIdAsync(5); res.Should().BeNull(); }
    [Fact] public async Task Service_Gift_Add_EmailAttempt_NoThrow() { var mock = new Mock<IGiftRepo>(); mock.Setup(r=>r.AddAsync(It.IsAny<Gift>())).ReturnsAsync((Gift?)new Gift{ IdGift=1}); var svc = new GiftService(mock.Object, Mock.Of<ILogger<GiftService>>(), Mock.Of<IConfiguration>(), Mock.Of<IEmailService1>(), Mock.Of<IUserRepo>()); var g = await svc.CreateGiftAsync(new GiftDTO{ Name="N"}); g.IdGift.Should().Be(1); }
    [Fact] public async Task Service_User_GetAll_Maps() { var mock = new Mock<IUserRepo>(); mock.Setup(r=>r.GetAllAsync()).ReturnsAsync((IEnumerable<User?>)new List<User?>{ (User?)new User{ Email="e@x.com"}}); var svc = new UserService(mock.Object, Mock.Of<IConfiguration>(), Mock.Of<ILogger<UserService>>() ); var res = await svc.GetAllAsync(); res.Should().ContainSingle(); }
    [Fact] public async Task Service_Order_UpdatePackage_ReturnsTrue() { var mock = new Mock<IOrderRepo>(); mock.Setup(r=>r.AddOrUpdatePackageInOrderAsync(It.IsAny<int>(),It.IsAny<int>(),It.IsAny<int>())).Returns(Task.CompletedTask); var svc = new OrderService(mock.Object, Mock.Of<IConfiguration>(), Mock.Of<ILogger<OrderService>>() ); var ok = await svc.UpdatePackageQuantityAsync(1,1,1); ok.Should().BeTrue(); }
    [Fact] public async Task Service_Order_GetById_NullHandled() { var mock = new Mock<IOrderRepo>(); mock.Setup(r=>r.GetByIdWithGiftsAsync(It.IsAny<int>())).ReturnsAsync((Order?)null); var svc = new OrderService(mock.Object, Mock.Of<IConfiguration>(), Mock.Of<ILogger<OrderService>>() ); var res = await svc.GetByIdWithGiftsAsync(1); res.Should().BeNull(); }
    [Fact] public async Task Service_Package_Delete_NoThrow() { var mock = new Mock<IPackageRepo>(); mock.Setup(r=>r.DeleteAsync(It.IsAny<int>())).Returns(Task.CompletedTask); var svc = new PackageService(mock.Object, Mock.Of<ILogger<PackageService>>() ); await svc.DeletePackageAsync(1); }
    [Fact] public async Task Service_Gift_GetParticipants_EmptyHandled() { var mock = new Mock<IGiftRepo>(); mock.Setup(r=>r.GetGiftWithOrdersAndUsersAsync(It.IsAny<int>())).ReturnsAsync((Gift?)null); var svc = new GiftService(mock.Object, Mock.Of<ILogger<GiftService>>(), Mock.Of<IConfiguration>(), Mock.Of<IEmailService1>(), Mock.Of<IUserRepo>()); var res = await svc.GetParticipantsDetailsAsync(1); res.Should().BeEmpty(); }
    [Fact] public async Task Service_User_Delete_ReturnsFalseIfMissing() { var mock = new Mock<IUserRepo>(); mock.Setup(r=>r.DeleteAsync(It.IsAny<int>())).ReturnsAsync(false); var svc = new UserService(mock.Object, Mock.Of<IConfiguration>(), Mock.Of<ILogger<UserService>>() ); var ok = await svc.DeleteAsync(1); ok.Should().BeFalse(); }

    // --- Controllers (14) ---
    [Fact] public async Task Controller_Donors_Update_ReturnsNoContent() { var mock = new Mock<IDonorService>(); mock.Setup(s=>s.UpdateDonorAsync(It.IsAny<int>(), It.IsAny<DonorCreateDTO>())).Returns(Task.CompletedTask); var ctrl = new DonorsController(mock.Object, Mock.Of<ILogger<DonorsController>>() ); var res = await ctrl.Update(1, new DonorCreateDTO{ FirstName="F"}); Assert.IsType<NoContentResult>(res); }
    [Fact] public async Task Controller_Donors_Delete_ReturnsNoContent() { var mock = new Mock<IDonorService>(); mock.Setup(s=>s.DeleteDonorAsync(It.IsAny<int>())).Returns(Task.CompletedTask); var ctrl = new DonorsController(mock.Object, Mock.Of<ILogger<DonorsController>>() ); var res = await ctrl.Delete(1); Assert.IsType<NoContentResult>(res); }
    [Fact] public async Task Controller_Gifts_GetById_ReturnsOk() { var mock = new Mock<IGiftService>(); mock.Setup(s=>s.GetGiftByIdAsync(It.IsAny<int>())).ReturnsAsync((Gift?)new Gift{ IdGift=1}); var ctrl = new GiftController(mock.Object, Mock.Of<IUserRepo>(), Mock.Of<ILogger<GiftController>>() ); var res = await ctrl.Get(1); Assert.IsType<OkObjectResult>(res); }
    [Fact] public async Task Controller_Gifts_Delete_NotFoundHandled() { var mock = new Mock<IGiftService>(); mock.Setup(s=>s.DeleteGiftAsync(It.IsAny<int>())).ReturnsAsync(false); var ctrl = new GiftController(mock.Object, Mock.Of<IUserRepo>(), Mock.Of<ILogger<GiftController>>() ); var res = await ctrl.Delete(1); Assert.IsType<NotFoundResult>(res); }
    [Fact] public async Task Controller_Packages_Create_ReturnsCreated() { var mock = new Mock<IPackageService>(); mock.Setup(s=>s.CreatePackageAsync(It.IsAny<PackageCreateDTO>())).ReturnsAsync((int)5); var ctrl = new PackagesController(mock.Object, Mock.Of<ILogger<PackagesController>>() ); var res = await ctrl.Create(new PackageCreateDTO{ Name="p"}); var c = Assert.IsType<CreatedAtActionResult>(res.Result); ((int)c.Value).Should().Be(5); }
    [Fact] public async Task Controller_Packages_Update_NoContent() { var mock = new Mock<IPackageService>(); mock.Setup(s=>s.UpdatePackageAsync(It.IsAny<int>(),It.IsAny<PackageCreateDTO>())).Returns(Task.CompletedTask); var ctrl = new PackagesController(mock.Object, Mock.Of<ILogger<PackagesController>>() ); var res = await ctrl.Update(1, new PackageCreateDTO{ Name="p"}); Assert.IsType<NoContentResult>(res); }
    [Fact] public async Task Controller_Orders_AddOrUpdateGift_Ok() { var mock = new Mock<IOrderService>(); mock.Setup(s=>s.AddOrUpdateGiftInOrderAsync(It.IsAny<int>(),It.IsAny<int>(),It.IsAny<int>())).ReturnsAsync(true); var ctrl = new OrdersController(mock.Object); var res = await ctrl.AddOrUpdateGift(new GiftUpdateDto{ UserId=1, GiftId=1, Amount=1 }); Assert.IsType<OkObjectResult>(res); }
    [Fact] public async Task Controller_Orders_Complete_ReturnsOk_WhenSuccess() { var mock = new Mock<IOrderService>(); mock.Setup(s=>s.CompleteOrder(It.IsAny<int>())).ReturnsAsync(true); var ctrl = new OrdersController(mock.Object); var res = await ctrl.CompleteOrder(1); Assert.IsType<OkObjectResult>(res); }
    [Fact] public async Task Controller_User_Login_ReturnsUnauthorizedOnNull() { var mock = new Mock<IUserService>(); mock.Setup(s=>s.LoginAsync(It.IsAny<string>(),It.IsAny<string>())).ReturnsAsync((string?)null); var ctrl = new UserController(mock.Object, Mock.Of<ILogger<UserController>>() ); var res = await ctrl.Login(new DtologinRequest{ Email="a@b", Password="p"}); Assert.IsType<UnauthorizedObjectResult>(res); }
    [Fact] public async Task Controller_User_GetAll_ReturnsOk() { var mock = new Mock<IUserService>(); mock.Setup(s=>s.GetAllAsync()).ReturnsAsync((IEnumerable<UserDTO?>)new List<UserDTO?>()); var ctrl = new UserController(mock.Object, Mock.Of<ILogger<UserController>>() ); var res = await ctrl.GetAllUsers(); Assert.IsType<OkObjectResult>(res); }
    [Fact] public async Task Controller_User_Delete_NotFoundHandled() { var mock = new Mock<IUserService>(); mock.Setup(s=>s.DeleteAsync(It.IsAny<int>())).ReturnsAsync(false); var ctrl = new UserController(mock.Object, Mock.Of<ILogger<UserController>>() ); var res = await ctrl.DeleteUser(1); Assert.IsType<NotFoundResult>(res); }
    [Fact] public async Task Controller_Gifts_DrawWinner_BadRequestWhenNull() { var mock = new Mock<IGiftService>(); mock.Setup(s=>s.DrawWinnerForGiftAsync(It.IsAny<int>())).ReturnsAsync((Winner?)null); var mockUserRepo = new Mock<IUserRepo>(); var ctrl = new GiftController(mock.Object, mockUserRepo.Object, Mock.Of<ILogger<GiftController>>() ); var res = await ctrl.DrawWinner(1); Assert.IsType<BadRequestObjectResult>(res); }
    [Fact] public async Task Controller_Packages_GetAll_ReturnsOk() { var mock = new Mock<IPackageService>(); mock.Setup(s=>s.GetAllPackagesAsync()).ReturnsAsync((IEnumerable<PackageDTO?>)new List<PackageDTO?>()); var ctrl = new PackagesController(mock.Object, Mock.Of<ILogger<PackagesController>>() ); var res = await ctrl.GetAll(); var ok = Assert.IsType<OkObjectResult>(res.Result); }
}
